management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  jmx:
    enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
logging:
  level:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
