spring:
  config:
    import: optional:file:./local.properties
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
    cookie:
      secure: false

frontend:
  url: "http://localhost:5173/callback"
bot-handler:
  fixed-rate: 1000 #  5초마다 실행
  corn : "0 0 0 * * *" # 매일 자정마다 호가
  order-level : 1,2,3,4,5 #오더북 단계 설정 - 주문량 증가
