otel:
  exporter:
    otlp:
      endpoint: http://monitoring-otel-collector:4318

  resource:
    attributes:
      service.name: monitoring-spring-app

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청을 trace로 기록

logging:
  level:
    io.opentelemetry: INFO
    io.micrometer.tracing: INFO
