spring:
  application:
    name: coin
  web:
    resources:
      add-mappings: false
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
order:
  tickers: BTC, TRUMP
