common-db-properties : &common-db-properties
  jdbc-url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password:

spring:
  config:
    import: optional:file:./local.properties
  datasource:
    main:
      <<: *common-db-properties
      hikari:
        maximum-pool-size: 13
        minimum-idle: 10
    trade:
      <<: *common-db-properties
      hikari:
        maximum-pool-size: 2
        minimum-idle: 2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
    cookie:
      secure: false

frontend:
  url: "http://localhost:5173/callback"

