management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 trace

opentelemetry:
  service:
    name: my-spring-app
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4318
  instrumentation:
    jdbc:
      enabled: false
