custom:
  datasource:
    main:
      init:
        mode: always
        data-locations: classpath:dataset/`if`.users.sql,classpath:dataset/`if`.account.sql,classpath:dataset/`if`.walletBTC.sql,classpath:dataset/`if`.walletTRUMP.sql
        platform: mariadb
