common-db-properties : &common-db-properties
    jdbc-url: jdbc:mariadb://${MARIADB_HOST}:3306/${MARIADB_DATABASE}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    main:
      <<: *common-db-properties
      pool-name: main-datasource-pool
      maximum-pool-size: 30
      minimum-idle: 30
    trade:
      <<: *common-db-properties
      pool-name: trade-datasource-pool
      maximum-pool-size: 3
      minimum-idle: 3
