management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
opentelemetry:
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4318
  service:
    name: my-app