service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
  jaeger_query:
    storage:
      traces: requests_store
  jaeger_storage:
    backends:
      requests_store:
        badger:
          directories:
            keys: "/tmp/jaeger/keys"
            values: "/tmp/jaeger/values"
          ephemeral: false
          consistency: true
          maintenance_interval: 1m0s

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: requests_store
